### ISSUE TITLE
Documentation references non-existant 'products' module

### ISSUE THREAD

**Issue by kkinder** [websanova/vue-store#1]
I like the idea you have here, as VueX can be a bit intimidating and involves an awful lot of boilerplate code to save you from writing direct code. ;)

The thing is, how are you supposed to use this? Your README file references a products module, but no such module exists in the repo. What's the usage?

Also, is this Vue 2 or 1?

**Comment by websanova** [comment]
The usage is right there, products is whatever you want it to be

module.exports = {

    // whatever you want here.

};

`products` just becomes the reference name in the store after that.

**Comment by websanova** [comment]
And yes, it's Vue2 tested only, I have kind of moved passed Vue 1 with my plugins, too much maintenance, and I find Vue2 is much more smoother/faster.

**Comment by kkinder** [comment]
It could be whatever you want it to be, but seeing the example you had in mind would make the code easier to follow.

**Comment by itmuse** [comment]
I have the some problem.
To install store to Vue :
`Vue.use(require('@websanova/vue-store'), {
    products: require('./store/products.js')
});`

and then call the products object
`this.$store.products`
 it return undefined. 
I check the code, products object is in `this.$store.watch.data`

**Comment by websanova** [comment]
You need to call it via get/set
