### ISSUE TITLE
unwatch

### ISSUE THREAD

**Issue by coderofsalvation** [websanova/vue-store#2]
Great minimal approach to vuex (personally i find the separation of mutator- and action-functions interesting, but this really makes the store-code very verbose).

what if watch certain store-variables in a component, and the component will be unmounted, and remounted again.
Will the store have duplicate watchers in that scenario?
Or are all watchers unmounted during umount..

**Comment by websanova** [comment]
Yea, so keep in mind this plugin is in very preliminary stage. And things
like this are specifically why I created it.

So...the idea was that it's method could be expanded. Like with a flag or
different method name.

**Comment by websanova** [comment]
Old post, but I've spent a bit of time on this, so this issue is addressed now.
